### ISSUE TITLE
Error: listen EACCES

### ISSUE THREAD

**Issue by RR07** [Deezloader/DeezLoader-Reborn#3]
$ cd DeezLoader-Reborn/app
$ node app.js
[Info]Server is running @ localhost:80
[Error]Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/data/data/com.termux/files/home/DeezLoader-Reborn/app/app.js:90:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
$

**Comment by XMB5** [comment]
Try using a port >1024
